apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: rl-lyrics-page
  name: rl-lyrics-page
  namespace: {{ meta.namespace }}
spec:
  replicas: 1
  selector:
    app: rl-lyrics-page
    deploymentconfig: rl-lyrics-page
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: rl-lyrics-page
        deploymentconfig: rl-lyrics-page
    spec:
      containers:
      - image: 'quay.io/right-lyrics/lyrics-page:1.0.0'
        name: rl-lyrics-page
        volumeMounts:
        - mountPath: /opt/app-root/src/config.js
          name: rl-lyrics-page
          subPath: config.js
      volumes:
      - configMap:
          defaultMode: 420
          name: rl-lyrics-page
        name: rl-lyrics-page
  triggers:
  - type: ConfigChange
