apiVersion: v1
kind: Service
metadata:
  labels:
    app: rl-lyrics-page
  name: rl-lyrics-page
  namespace: {{ meta.namespace }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rl-lyrics-page
    deploymentconfig: rl-lyrics-page
  type: ClusterIP