apiVersion: v1
kind: List
metadata:
  name: right-lyrics-builds
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: rl-lyrics-service
    name: rl-lyrics-service
  spec:
    output:
      to:
        kind: DockerImage
        name: quay.io/right-lyrics/lyrics-service:1.0
      pushSecret:
        name: rl-quay-credentials
    runPolicy: Serial
    source:
      contextDir: lyrics-service
      git:
        uri: https://github.com/leandroberetta/right-lyrics.git
        ref: master
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:8
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: rl-songs-service
    name: rl-songs-service
  spec:
    output:
      to:
        kind: DockerImage
        name: quay.io/right-lyrics/songs-service:1.1
      pushSecret:
        name: rl-quay-credentials
    source:
      contextDir: songs-service
      git:
        uri: https://github.com/leandroberetta/right-lyrics.git
        ref: master
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: redhat-openjdk18-openshift:1.5
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: rl-lyrics-page-builder
    name: rl-lyrics-page-builder
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: rl-lyrics-page-builder
    name: rl-lyrics-page-builder
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: rl-lyrics-page-builder:latest
    source:
      contextDir: lyrics-page
      git:
        uri: https://github.com/leandroberetta/right-lyrics.git
        ref: master
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:10
          namespace: openshift
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: rl-lyrics-page
    name: rl-lyrics-page
  spec:
    output:
      to:
        kind: DockerImage
        name: quay.io/right-lyrics/lyrics-page:1.2
      pushSecret:
        name: rl-quay-credentials
    source:
      images:
      - as: null
        from:
          kind: ImageStreamTag
          name: rl-lyrics-page-builder:latest
        paths:
        - destinationDir: .
          sourcePath: /opt/app-root/src/build/.
      type: Image
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nginx:1.12
          namespace: openshift
      type: Source
    triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: rl-lyrics-page-builder:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: rl-hits-service
    name: rl-hits-service
  spec:
    output:
      to:
        kind: DockerImage
        name: quay.io/right-lyrics/hits-service:1.0
      pushSecret:
        name: rl-quay-credentials
    runPolicy: Serial
    source:
      contextDir: hits-service
      git:
        uri: https://github.com/leandroberetta/right-lyrics.git
        ref: master
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - type: ImageChange
