apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rightlyrics.veicot.io
spec:
  group: veicot.io
  names:
    kind: RightLyrics
    listKind: RightLyricsList
    plural: rightlyrics
    singular: rightlyrics
    shortNames:
    - rl  
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
