apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: songs-pipeline
spec:
  workspaces:
    - name: source
  tasks:
    - name: clone
      taskRef:
        name: git
      workspaces:
        - name: source
          workspace: source
      params:
        - name: REPOSITORY
          value: https://github.com/leandroberetta/right-lyrics
        - name: REVISION
          value: refactor    
    - name: build
      taskRef:
        name: s2i
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: example.org/right-lyrics/songs-service:latest
        - name: BASE_IMAGE
          value: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
        - name: BASE_IMAGE_S2I_SCRIPTS
          value: /usr/local/s2i
        - name: CONTEXT_PATH
          value: songs-service
        - name: TLS_VERIFY
          value: "false"
        - name: FORMAT
          value: docker
    - name: deploy
      taskRef:
        name: kubectl
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: apply -k $(workspaces.source.path)/songs-service/k8s/overlays/local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-source
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi