apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: albums-pipeline
spec:
  workspaces:
    - name: source
  tasks:
    - name: clone
      taskRef:
        name: git
      workspaces:
        - name: source
          workspace: source
      params:
        - name: REPOSITORY
          value: https://github.com/leandroberetta/right-lyrics
        - name: REVISION
          value: refactor
    - name: package
      taskRef:
        name: mvn
      runAfter:
      - clone
      workspaces:
      - name: source
        workspace: source
      params:
      - name: COMMAND
        value: package
      - name: CONTEXT_PATH
        value: albums-service
    - name: build
      taskRef:
        name: buildah
      runAfter:
      - package
      workspaces:
      - name: source
        workspace: source
      params:
      - name: IMAGE
        value: example.org/right-lyrics/albums-service:latest
      - name: CONTEXT_PATH
        value: albums-service
      - name: TLS_VERIFY
        value: "false"
      - name: FORMAT
        value: docker              
    - name: deploy
      taskRef:
        name: kubectl
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: apply -k $(workspaces.source.path)/songs-service/k8s/overlays/local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: albums-source
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi