apiVersion: apps/v1
kind: Deployment
metadata:
  name: albums-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: albums-service
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              memory: 256Mi
              cpu: 200m
