apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: page-pipeline
spec:
  workspaces:
    - name: source
  tasks:
    - name: clone
      taskRef:
        name: git
      workspaces:
        - name: source
          workspace: source
      params:
        - name: REPOSITORY
          value: https://github.com/leandroberetta/right-lyrics
        - name: REVISION
          value: refactor
    - name: install
      taskRef:
        name: npm
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: install
        - name: CONTEXT_PATH
          value: lyrics-page
    - name: generate
      taskRef:
        name: npm
      runAfter:
        - install
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: run-script build
        - name: CONTEXT_PATH
          value: lyrics-page  
    - name: build
      taskRef:
        name: s2i
      runAfter:
        - generate
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: example.org/right-lyrics/lyrics-service:latest
        - name: BASE_IMAGE
          value: registry.access.redhat.com/rhscl/nginx-114-rhel7
        - name: CONTEXT_PATH
          value: lyrics-page/build
        - name: TLS_VERIFY
          value: "false"
        - name: FORMAT
          value: docker
    - name: deploy
      taskRef:
        name: kubectl
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: apply -k $(workspaces.source.path)/lyrics-service/k8s/overlays/local