apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rl-hits-service
  name: rl-hits-redis-data
  namespace: {{ meta.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi