apiVersion: v1
kind: Service
metadata:
  labels:
    app: rl-hits-service
  name: rl-hits-redis
  namespace: {{ meta.namespace }}
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: rl-hits-redis
  type: ClusterIP