apiVersion: v1
kind: ConfigMap
metadata:
  name: rl-songs-postgresql-import
  namespace: {{ meta.namespace }}
data:
  songs.sql: |
    CREATE TABLE IF NOT EXISTS song (
        id bigint NOT NULL,
        artist character varying(255),
        lyric_id character varying(255),
        name character varying(255)
    );

    ALTER TABLE ONLY song ADD CONSTRAINT song_pkey PRIMARY KEY (id);

    INSERT INTO song (id, name, artist, lyric_id) VALUES (1, 'Californication', 'Red Hot Chili Peppers', '5d72534eef68ea00194ac5e8') ON CONFLICT DO NOTHING;
    INSERT INTO song (id, name, artist, lyric_id) VALUES (2, 'Everlong', 'Foo Fighters', '5d72535def68ea00194ac5ea') ON CONFLICT DO NOTHING;
    INSERT INTO song (id, name, artist, lyric_id) VALUES (3, 'Even Flow', 'Pearl Jam', '5d725355ef68ea00194ac5e9') ON CONFLICT DO NOTHING;