apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: rl-songs-service
  name: rl-songs-postgresql
  namespace: {{ meta.namespace }}
spec:
  replicas: 1
  selector:
    name: rl-songs-postgresql
  strategy:
    recreateParams:
      post:
        execNewPod:
          command:
          - /bin/sh
          - -i
          - -c
          - PGPASSWORD=right-lyrics psql -U right-lyrics -h rl-songs-postgresql -d
            right-lyrics -f /tmp/data/songs.sql
          containerName: postgresql
          volumes:
          - rl-songs-postgresql-data
        failurePolicy: Abort
    type: Recreate
  template:
    metadata:
      labels:
        app: rl-songs-service
        name: rl-songs-postgresql
    spec:
      containers:
      - env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: rl-songs-postgresql
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: rl-songs-postgresql
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: rl-songs-postgresql
        image: ''
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
            - --live
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/libexec/check-container
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        volumeMounts:
        - mountPath: /tmp/data
          name: rl-songs-postgresql-data
      volumes:
      - configMap:
          name: rl-songs-postgresql-data
        name: rl-songs-postgresql-data
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - postgresql
      from:
        kind: ImageStreamTag
        name: postgresql:10
        namespace: openshift
    type: ImageChange
  - type: ConfigChange