apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rl-songs-service
  name: rl-songs-postgresql-data
  namespace: {{ meta.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi