apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: rl-lyrics-page
  name: rl-lyrics-page
  namespace: {{ meta.namespace }}
spec:
  replicas: {{ lyrics_page_replicas }}
  selector:
    app: rl-lyrics-page
    deploymentconfig: rl-lyrics-page
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: rl-lyrics-page
        deploymentconfig: rl-lyrics-page
    spec:
      containers:
      - image: 'quay.io/right-lyrics/lyrics-page:1.0'
        name: rl-lyrics-page
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
        volumeMounts:
        - mountPath: /opt/app-root/src/config.js
          name: rl-lyrics-page
          subPath: config.js
      volumes:
      - configMap:
          defaultMode: 420
          name: rl-lyrics-page
        name: rl-lyrics-page
  triggers:
  - type: ConfigChange
