apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/connects-to: rl-songs-service,rl-lyrics-service
  labels:
    app: rl-lyrics-page
    app.openshift.io/runtime: nginx
    app.kubernetes.io/part-of: right-lyrics
  name: rl-lyrics-page
  namespace: {{ meta.namespace }}
spec:
  replicas: {{ lyrics_page_replicas }}
  selector:
    app: rl-lyrics-page
    deploymentconfig: rl-lyrics-page
  strategy:
    type: Rolling
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: rl-lyrics-page
        deploymentconfig: rl-lyrics-page
    spec:
      containers:
      - image: quay.io/right-lyrics/lyrics-page:1.2
        name: rl-lyrics-page
        imagePullPolicy: Always
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
        volumeMounts:
        - mountPath: /etc/opt/rh/rh-nginx112/nginx/nginx.conf
          name: rl-lyrics-page
          subPath: nginx.conf
      volumes:
      - configMap:
          defaultMode: 420
          name: rl-lyrics-page
        name: rl-lyrics-page
  triggers:
  - type: ConfigChange
