apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/connects-to: rl-hits-redis
  labels:
    app: rl-hits-service
    app.openshift.io/runtime: python
    app.kubernetes.io/part-of: right-lyrics
  name: rl-hits-service
  namespace: {{ meta.namespace }}
spec:
  replicas: {{ hits_service_replicas }}
  selector:
    app: rl-hits-service
    deploymentconfig: rl-hits-service
  strategy:
    type: Rolling
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"    
      labels:
        app: rl-hits-service
        deploymentconfig: rl-hits-service
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: rl-hits-redis
        - name: DB_PASSWORD
          value: right-lyrics
        image: quay.io/right-lyrics/hits-service:1.0
        imagePullPolicy: Always
        name: rl-hits-service
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
        ports:
        - containerPort: 8080
          protocol: TCP
  triggers:
  - type: ConfigChange