apiVersion: v1
kind: Route
metadata:
  labels:
    app: rl-hits-service
  name: rl-hits-service
  namespace: {{ meta.namespace }}
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: rl-hits-service