apiVersion: v1
kind: Service
metadata:
  labels:
    app: rl-hits-service
  name: rl-hits-service
  namespace: {{ meta.namespace }}
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rl-hits-service
    deploymentconfig: rl-hits-service
  type: ClusterIP