apiVersion: v1
kind: Secret
metadata:
  labels:
    app: rl-lyrics-service
  name: rl-lyrics-mongodb
  namespace: {{ meta.namespace }}
stringData:
  database-admin-password: right-lyrics
  database-name: right-lyrics
  database-password: right-lyrics
  database-user: right-lyrics
type: Opaque