apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: albums-pipeline
spec:
  workspaces:
    - name: source
  tasks:
    - name: clone
      taskRef:
        name: git
      workspaces:
        - name: source
          workspace: source
      params:
        - name: REPOSITORY
          value: https://github.com/leandroberetta/right-lyrics
        - name: REVISION
          value: master
    - name: build
      taskRef:
        name: s2i
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/right-lyrics/albums-service:latest
        - name: BASE_IMAGE
          value: registry.access.redhat.com/ubi8/openjdk-11:latest
        - name: BASE_IMAGE_S2I_SCRIPTS
          value: /usr/local/s2i
        - name: CONTEXT_PATH
          value: albums-service
        - name: TLS_VERIFY
          value: "false"
        - name: FORMAT
          value: docker
        - name: INCREMENTAL
          value: "false"      
    - name: deploy
      taskRef:
        name: kubectl
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: apply -k $(workspaces.source.path)/albums-service/k8s/overlays/dev