apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: page-pipeline
spec:
  params:
    - name: GIT_REPOSITORY
      default: https://github.com/leandroberetta/right-lyrics
    - name: GIT_REVISION
      default: master
    - name: IMAGE
      default: example.org/right-lyrics/lyrics-page:latest
  workspaces:
    - name: source
  tasks:
    - name: clone
      taskRef:
        name: git
      workspaces:
        - name: source
          workspace: source
      params:
        - name: REPOSITORY
          value: $(params.GIT_REPOSITORY)
        - name: REVISION
          value: $(params.GIT_REVISION)
    - name: install
      taskRef:
        name: npm
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: install
        - name: CONTEXT_PATH
          value: lyrics-page
    - name: generate
      taskRef:
        name: npm
      runAfter:
        - install
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: run build
        - name: CONTEXT_PATH
          value: lyrics-page  
    - name: build
      taskRef:
        name: s2i
      runAfter:
        - generate
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: BASE_IMAGE
          value: registry.access.redhat.com/rhscl/nginx-114-rhel7
        - name: CONTEXT_PATH
          value: lyrics-page/build
        - name: TLS_VERIFY
          value: "false"
        - name: FORMAT
          value: docker    
    - name: apply-manifests
      taskRef:
        name: kubectl
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: apply -k $(workspaces.source.path)/lyrics-page/k8s
    - name: pause-rollout
      taskRef:
        name: kubectl
      runAfter:
        - apply-manifests
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: rollout pause deployment lyrics-page
    - name: set-image
      taskRef:
        name: kubectl
      runAfter:
        - pause-rollout
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: set image deployment lyrics-page lyrics-page=$(params.IMAGE)
    - name: set-last-restart
      taskRef:
        name: kubectl
      runAfter:
        - set-image
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: patch deployment/lyrics-page --patch "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"last-restart\":\"`date +'%s'`\"}}}}}"
    - name: resume-rollout
      taskRef:
        name: kubectl
      runAfter:
        - set-last-restart
      workspaces:
        - name: source
          workspace: source
      params:
        - name: COMMAND
          value: rollout resume deployment lyrics-page
