apiVersion: v1
kind: Service
metadata:
  labels:
    app: rl-lyrics-service
  name: rl-lyrics-mongodb
  namespace: {{ meta.namespace }}
spec:
  ports:
  - name: tcp-27017
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: rl-lyrics-mongodb
  type: ClusterIP