apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: rl-songs-service
  name: rl-songs-service
  namespace: {{ meta.namespace }}
spec:
  replicas: {{ songs_service_replicas }}
  selector:
    app: rl-songs-service
    deploymentconfig: rl-songs-service
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: rl-songs-service
        deploymentconfig: rl-songs-service
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_PASSWORD
          value: right-lyrics
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://rl-songs-postgresql:5432/right-lyrics
        - name: SPRING_DATASOURCE_USERNAME
          value: right-lyrics
        image: 'quay.io/right-lyrics/songs-service:1.0'
        name: rl-songs-service
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
  triggers:
  - type: ConfigChange
