apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: rl-lyrics-service
  name: rl-lyrics-service
  namespace: {{ meta.namespace }}
spec:
  replicas: {{ lyrics_service_replicas }}
  selector:
    app: rl-lyrics-service
    deploymentconfig: rl-lyrics-service
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: rl-lyrics-service
        deploymentconfig: rl-lyrics-service
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: rl-lyrics-mongodb
        - name: DB_NAME
          value: right-lyrics
        - name: DB_PASSWORD
          value: right-lyrics
        - name: DB_USERNAME
          value: right-lyrics
        image: 'quay.io/right-lyrics/lyrics-service:1.0'
        name: rl-lyrics-service
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
        ports:
        - containerPort: 8080
          protocol: TCP
  triggers:
  - type: ConfigChange