apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/connects-to: rl-songs-postgresql,rl-hits-service
  labels:
    app: rl-songs-service
    app.openshift.io/runtime: java
    app.kubernetes.io/part-of: right-lyrics
  name: rl-songs-service
  namespace: {{ meta.namespace }}
spec:
  replicas: {{ songs_service_replicas }}
  selector:
    app: rl-songs-service
    deploymentconfig: rl-songs-service
  strategy:
    type: Rolling
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: rl-songs-service
        deploymentconfig: rl-songs-service
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_PASSWORD
          value: right-lyrics
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://rl-songs-postgresql:5432/right-lyrics
        - name: SPRING_DATASOURCE_USERNAME
          value: right-lyrics
        - name: HITS_SERVICE_URL
          value: http://rl-hits-service:8080
        image: 'quay.io/right-lyrics/songs-service:1.1'
        name: rl-songs-service
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
  triggers:
  - type: ConfigChange
