apiVersion: v1
kind: Service
metadata:
  labels:
    app: rl-songs-service
  name: rl-songs-service
  namespace: {{ meta.namespace }}
spec:
  ports:
  - name: tcp-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rl-songs-service
    deploymentconfig: rl-songs-service
  type: ClusterIP