  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: import-service
spec:
  template:
    spec:
      containers:
        - name: import-service
          image: example.org/right-lyrics/import-service:latest