apiVersion: v1
kind: Secret
metadata:
  labels:
    app: rl-songs-service
  name: rl-songs-postgresql
  namespace: {{ meta.namespace }}
stringData:
  database-name: right-lyrics
  database-password: right-lyrics
  database-user: right-lyrics
type: Opaque