apiVersion: v1
kind: Service
metadata:
  labels:
    app: rl-songs-service
  name: rl-songs-postgresql
  namespace: {{ meta.namespace }}
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: rl-songs-postgresql
  type: ClusterIP